server:
  port: 8080
  servlet:
    context-path: /showtime
spring:
  datasource:
    username: root
    password: yu7230380
    url: jdbc:mysql://localhost:3306/showtime?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver